package com.aespen.stickynotes.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.aespen.stickynotes.dao.user;
import com.aespen.stickynotes.dao.note;

import com.aespen.stickynotes.dao.userDao;
import com.aespen.stickynotes.dao.noteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig noteDaoConfig;

    private final userDao userDao;
    private final noteDao noteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(userDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(noteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        userDao = new userDao(userDaoConfig, this);
        noteDao = new noteDao(noteDaoConfig, this);

        registerDao(user.class, userDao);
        registerDao(note.class, noteDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        noteDaoConfig.getIdentityScope().clear();
    }

    public userDao getUserDao() {
        return userDao;
    }

    public noteDao getNoteDao() {
        return noteDao;
    }

}
